[package]
name = "yanet-cli-device-vlan"
version = "0.1.0"
edition = "2024"
publish = false

rust-version = "1.85"

[dependencies]
ync = { path = "../../../cli/core", version = "0.1", package = "yanet-cli"}
clap = { version = "4.5", features = ["derive"] }
clap_complete = { version = "4.5", features = ["unstable-dynamic"] }
colored = "3"
ipnet = "2"
log = "0.4"
prost = "0.13"
prost-types = "0.13"
ptree = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt", "net", "time", "macros", "sync"] }
tonic = "0.13"

[build-dependencies]
tonic-build = "0.13.0"
