[package]
name = "yanet-cli-balancer"
version = "0.1.0"
edition = "2024"
publish = false

rust-version = "1.85"

[dependencies]
ync = { path = "../../../cli/core", version = "0.1", package = "yanet-cli" }
clap = { version = "4.5", features = ["derive"] }
clap_complete = { version = "4.5", features = ["unstable-dynamic"] }
tokio = { version = "1", features = ["rt", "net", "time", "macros", "sync"] }
tonic = "0.13"
prost = "0.13"
prost-types = "0.13"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
ptree = "0.5"
tabled = "0.17"
colored = "3"
log = "0.4"
ipnet = "2"
chrono = "0.4"

[build-dependencies]
tonic-build = "0.13"

[lib]
name = "yanet_cli_balancer"
path = "src/lib.rs"
