[package]
name = "yanet-cli-dscp"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
clap_complete = "4.5"
log = "0.4"
ipnet = "2"
colored = "3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["rt", "macros"] }
tonic = { version = "0.13", features = ["gzip"] }
prost = "0.13"
ptree = "0.5"
ync = { path = "../../../cli/core", version = "0.1", package = "yanet-cli" }

[build-dependencies]
tonic-build = "0.13" 
